import "@/styles/globals.css";

import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { fontDigital, fontDisplay, fontMono } from "@/lib/fonts";
import { AppHeader } from "./_components/AppHeader";
import { ContentWrap } from "../_components/ContentWrap";

export const metadata = {
  title: "Workout Deck",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-mono ${fontDisplay} ${fontMono} ${fontDigital}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TRPCReactProvider>
            <div className="grid gap-6">
              <ContentWrap>
                <AppHeader />
              </ContentWrap>

              {children}
            </div>
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
